spring:
  profiles:
    default: default
server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: test
server:
  port: 9090